spring:
  config:
    ant:
      server:
        host-url: http://abc.com
        polling:
          path: /hb
          method: GET
      client:
        cache-file-path: /home/work/spring_config_ant/server_data.dat
